# Generated by Django 6.0.7 on 2026-07-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_return', to='sales.sale')),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
    ]
