# Generated by Django 6.0.7 on 2026-07-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salereturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salereturn',
            options={'ordering': ['-returned_at'], 'verbose_name': 'Sale Return', 'verbose_name_plural': 'Sale Returns'},
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='returned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
