# Generated by Django 6.0.7 on 2026-07-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='model_name',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20),
        ),
    ]
